function export_globally_fish_colors_dark
  set -gx -- fish_color_auto_suggestion                             -- 'brblack'
  set -gx -- fish_color_cancel          --reverse                   -- 'normal'
  set -gx -- fish_color_command                                     -- '005FD7'
  set -gx -- fish_color_comment                                     -- '990000'
  set -gx -- fish_color_cwd                                         -- 'C3C3C3'
  set -gx -- fish_color_cwd_root                                    -- 'red'
  set -gx -- fish_color_end                                         -- '009900'
  set -gx -- fish_color_error                                       -- 'FF0000'
  set -gx -- fish_color_escape                                      -- '00A6B2'
  set -gx -- fish_color_hg_added                                    -- 'green'
  set -gx -- fish_color_hg_clean                                    -- 'green'
  set -gx -- fish_color_hg_copied                                   -- 'magenta'
  set -gx -- fish_color_hg_deleted                                  -- 'red'
  set -gx -- fish_color_hg_dirty                                    -- 'red'
  set -gx -- fish_color_hg_modified                                 -- 'yellow'
  set -gx -- fish_color_hg_renamed                                  -- 'magenta'
  set -gx -- fish_color_hg_unmerged                                 -- 'red'
  set -gx -- fish_color_hg_untracked                                -- 'yellow'
  set -gx -- fish_color_history_current --bold                      -- 'normal'
  set -gx -- fish_color_host                                        -- 'normal'
  set -gx -- fish_color_host_remote                                 -- 'normal'
  set -gx -- fish_color_keyword         --bold                      -- 'FF5000'
  set -gx -- fish_color_normal                                      -- 'normal'
  set -gx -- fish_color_operator                                    -- '00A6B2'
  set -gx -- fish_color_option                                      -- '80D800'
  set -gx -- fish_color_param                                       -- '00AFFF'
  set -gx -- fish_color_quote                                       -- '999900'
  set -gx -- fish_color_redirection                                 -- 'D200D2'
  set -gx -- fish_color_search_match    --background=brblack        -- 'bryellow'
  set -gx -- fish_color_selection       --background=brblack --bold -- 'white'
  set -gx -- fish_color_status                                      -- 'red'
  set -gx -- fish_color_user                                        -- 'FF6211'
  set -gx -- fish_color_valid_path      --bold                      -- 'brcyan'
end
