function export_globally_fish_colors_light
  set -gx -- fish_color_auto_suggestion                             -- 'brblack'
  set -gx -- fish_color_cancel          --reverse                   -- 'normal'
  set -gx -- fish_color_command                                     -- '0042B4'
  set -gx -- fish_color_comment                                     -- '990000'
  set -gx -- fish_color_cwd                                         -- '737373'
  set -gx -- fish_color_cwd_root                                    -- 'red'
  set -gx -- fish_color_end                                         -- '004200'
  set -gx -- fish_color_error                                       -- 'FF0000'
  set -gx -- fish_color_escape                                      -- 'E400A6'
  set -gx -- fish_color_hg_added                                    -- 'green'
  set -gx -- fish_color_hg_clean                                    -- 'green'
  set -gx -- fish_color_hg_copied                                   -- 'magenta'
  set -gx -- fish_color_hg_deleted                                  -- 'red'
  set -gx -- fish_color_hg_dirty                                    -- 'red'
  set -gx -- fish_color_hg_modified                                 -- 'yellow'
  set -gx -- fish_color_hg_renamed                                  -- 'magenta'
  set -gx -- fish_color_hg_unmerged                                 -- 'red'
  set -gx -- fish_color_hg_untracked                                -- 'yellow'
  set -gx -- fish_color_history_current --bold                      -- 'normal'
  set -gx -- fish_color_host                                        -- 'normal'
  set -gx -- fish_color_host_remote                                 -- 'normal'
  set -gx -- fish_color_keyword         --bold                      -- 'FF5000'
  set -gx -- fish_color_normal                                      -- 'normal'
  set -gx -- fish_color_operator                                    -- '008391'
  set -gx -- fish_color_option                                      -- '387400'
  set -gx -- fish_color_param                                       -- '1085D0'
  set -gx -- fish_color_quote                                       -- '737300'
  set -gx -- fish_color_redirection                                 -- 'A300D2'
  set -gx -- fish_color_search_match    --background=brblack        -- 'bryellow'
  set -gx -- fish_color_selection       --background=brblack --bold -- 'white'
  set -gx -- fish_color_status                                      -- 'red'
  set -gx -- fish_color_user            --bold                      -- 'E55100'
  set -gx -- fish_color_valid_path      --bold                      -- 'brcyan'
end
